version: '3.8'

services:
  web:
    build: 
      context: ../apps/web
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    depends_on: 
      - api
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  api:
    build: 
      context: ../apps/api
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_DSN=postgres://ielts_user:ielts_password@db:5432/ielts_db?sslmode=disable
      - JWT_SECRET=supersecret_change_in_production
      - AI_PROVIDER=openai
      - AI_KEY=${AI_KEY}
      - RATE_LIMIT_PER_MIN=30
      - PUBLIC_BASE_URL=https://yourdomain.com
      - REDIS_URL=redis://redis:6379
    depends_on: 
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ielts_db
      POSTGRES_USER: ielts_user
      POSTGRES_PASSWORD: ielts_password
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
      - "443:443"
    depends_on: 
      - web
      - api
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
